### ISSUE TITLE
Parcel issues

### ISSUE THREAD

**Issue by jtremback** [aragon/aragon-react-boilerplate#15]
I believe that https://github.com/parcel-bundler/parcel/issues/1586 may be the cause of https://github.com/aragon/aragon-cli/issues/149

**Comment by jtremback** [comment]
Upgrading to 1.9.3 seems to have fixed this somewhat, but i'm still seeing problems with .map files not getting updated

**Comment by jtremback** [comment]
After doing `aragon run`, parcel outputs a js file and a map file that do not match.
Here's what the `dist` folder looks like:

```
dist
├── aragon-ui
├── index.html
├── main.251b65d6.js
├── main.a3dcdc7a.map
├── script.js
└── script.map
```
I have been unable to reproduce this with parcel running in a new project (not aragon), so I'm hesitant to file it with parcel, although it is probably a parcel issue.

**Comment by jtremback** [comment]
After doing `aragon run`, in addition to the above issue, my app is crashing with `Uncaught TypeError: (0 , h.default) is not a function`

Deleting `.cache` and `dist` before building seems to solve this issue (however, the issue with the js file and the map file not matching still persists).

I've generally gotten the feel that parcel is pretty janky. Maybe just bad luck. If this persists much longer I may end up making a create-react-app based bootstrap, which would be a shame since so much work has gone into this bootstrap.

**Comment by sohkai** [comment]
That's definitely weird and I haven't seen it myself. I'll first update the parcel dependency here and then see if I can reproduce this locally.

**Comment by sohkai** [comment]
Closing with #16.
