### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by cslarson** [aragon/aragon-react-boilerplate#36]
Following the directions in the Readme, and with Metamask switch to rpc `http://localhost:8545`, the app loads up and displays `Organization not found`. Looking in the dev console, there is a connection error:

`WebSocket connection to 'ws://localhost:7545/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

**Comment by sohkai** [comment]
Hmm, this seems quite weird; did it say it was trying to connect to `localhost:7545` (not `8545`)?

**Comment by cslarson** [comment]
yes, but why? everywhere is referencing port 8545: truffle.js, the console.

```
 ℹ This is the configuration for your development deployment:
    Ethereum Node: ws://localhost:8545
    ENS registry: 0x5f6f7e8cc7346a11ca2def8f827b7a0b612c56a1
    APM registry: aragonpm.eth
    DAO address: 0x5b6a3301a67A4bfda9D3a528CaD34cac6e7F8070

    Opening http://localhost:3000/#/0x5b6a3301a67A4bfda9D3a528CaD34cac6e7F8070 to view your DAO
```

**Comment by cslarson** [comment]
I had the `REACT_APP_DEFAULT_ETH_NODE` environment variable set (in my .bashrc) to `ws://localhost:7545`, probably from a time looking into Aragon a while back. Completely forgot about it!
