### ISSUE TITLE
IPFS error: no link named "index.html"

### ISSUE THREAD

**Issue by ElenaPT** [aragon/aragon-react-boilerplate#76]
Hi,

I have encountered a problem while trying to run the boilerplate.

I have followed the instructions in the readme, and the DAO starts properly, but the Counter interface does not load. Instead, the following error message is shown:

```
ipfs resolve -r /ipfs/QmbDVxipAuZaBjek9JTgcVExTvcnVx9KosEn9iMAwRcMdK/index.html: no link named "index.html" under QmbDVxipAuZaBjek9JTgcVExTvcnVx9KosEn9iMAwRcMdK
```

**Comment by sembrestels** [comment]
Downgrading the `@aragon/cli` version to 5.9.2 solves the problem.

**Comment by dstreppa** [comment]
The same for me

**Comment by sembrestels** [comment]
This issue is related with https://github.com/aragon/aragon-react-boilerplate/commit/405da7aedf8e4264b2ca6e37af17f9a1227c625a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R33 but I can't reproduce it.

By the way, I have problems when trying to run `start:ipfs:template`. The following error ocurrs:
```
  ❯ Create DAO
    ✖ Create new DAO from template
      → Cannot read property 'returnValues' of undefined
```

**Comment by sembrestels** [comment]
@ElenaPT @dstreppa: As a workarround, you can do:

```sh
git clone https://github.com/aragon/aragon-react-boilerplate your-app
cd your-app
git checkout 703be749b380
npm install
npm start # or npm run start:ipfs:template for running the Template
```

**Comment by 0xGabi** [comment]
@dstreppa sorry about that, will look into this over the weekend.

Thanks @sembrestels for the workaround 🙏

**Comment by 0xGabi** [comment]
Hey @dstreppa @ElenaPT this was an issue with the way the new version of the aragonCLI handle the files to be publish. We release a patch to keep backward compatible. At the same time we update the `start:ipfs` node script to be: `aragon run --files dist`

Note: Specify the minimum content is important cause this information will be propagated to IPFS eventually. The `--files` flag allow to choose wich content include in the publication
