### ISSUE TITLE
Add smart contracts security best practices reference

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-react-boilerplate#85]
[Mythril](https://github.com/ConsenSys/mythril) seems to be the standard for this but we could explore additional options

**Comment by sohkai** [comment]
I wouldn't bother adding on yet, since our experiences with them are pretty lackluster. We can add a section in the readme to go read things like the [best practices](https://github.com/ConsenSys/smart-contract-best-practices), which also include tips for security tooling.

**Comment by 0xGabi** [comment]
We can close this for now
