### ISSUE TITLE
React error when importing aragonUI components

### ISSUE THREAD

**Issue by evvvritt** [aragon/aragon-react-boilerplate#89]
Hi, importing several aragonUI components into `App.js` per the [docs](https://ui.aragon.org/) produces the following error:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
    in App
    in AragonApi
```
Error on: **Header**, **Box**, **Bar**, ...
No error: **Button**, **Table**, ...

### Steps to Reproduce
1. clone repo
2. `npm install`
3. `npm run prepare`
4. `npm run start:app`
5. `npm run start:http`
6. Add aragonUI component [Box](https://ui.aragon.org/box/) to `App.js`:
```
// App.js

import React from 'react'
import { Main, Button, Box } from '@aragon/ui'
...

function App() {
  return (
    <Main>
      <Box>Primary content</Box>
      ...
    </Main>
  )
}
...
```
Is there a step that's missing when importing components?

**Comment by 0xGabi** [comment]
Related to #87

**Comment by evvvritt** [comment]
Thanks! no issues when upgrading @aragon/ui to 1.0.0
